import { LegalDocument, type LegalSection } from '@/components/legal/LegalDocument'

const sections: LegalSection[] = [
  {
    heading: '1. About ShTrader',
    blocks: [
      'ShTrader is a technology platform providing tools and services for market analysis, trading education, risk management, artificial-intelligence-assisted market analysis, and blockchain-based trading functionality.',
      'ShTrader is a technology platform. Unless expressly stated otherwise, ShTrader does not act as your financial adviser, investment adviser, broker, dealer, fiduciary, or portfolio manager.',
    ],
  },
  {
    heading: '2. Eligibility',
    blocks: [
      'You must be legally permitted to use the Service in your jurisdiction.',
      'By using ShTrader, you represent that:',
      {
        list: [
          'you are legally capable of entering into these Terms;',
          'you are not prohibited from using the Service under applicable law;',
          'the information you provide to ShTrader is accurate and not misleading; and',
          'you will comply with all applicable laws and regulations when using the Service.',
        ],
      },
      'ShTrader may restrict access to particular features, markets, countries, or users where required by applicable law or platform requirements.',
    ],
  },
  {
    heading: '3. No Financial or Investment Advice',
    blocks: [
      'Information provided through ShTrader, including market analysis, trading signals, AI-generated analysis, charts, educational materials, risk calculations, and other trading-related information, is provided for informational and educational purposes.',
      'Nothing provided by ShTrader constitutes:',
      {
        list: [
          'investment advice;',
          'financial advice;',
          'trading advice;',
          'a recommendation to buy or sell an asset;',
          'a guarantee of profit;',
          'a guarantee that a trading strategy will succeed; or',
          'a guarantee regarding future market movements.',
        ],
      },
      'You are solely responsible for your trading and investment decisions.',
      'Past performance does not guarantee future results.',
    ],
  },
  {
    heading: '4. Trading and Market Risk',
    blocks: [
      'Trading foreign exchange, cryptocurrency, commodities, and other financial instruments involves substantial risk.',
      'You may lose some or all of the funds committed to a transaction.',
      'Market prices may change rapidly and unexpectedly. Liquidity, spreads, slippage, network conditions, oracle availability, technical failures, and other factors may affect transactions and their outcomes.',
      'You should only use funds that you can afford to lose.',
    ],
  },
  {
    heading: '5. Artificial Intelligence Features',
    blocks: [
      'ShTrader may use artificial intelligence and machine-learning systems to generate market analysis, trading signals, summaries, risk information, educational content, or other outputs.',
      'AI-generated information may be inaccurate, incomplete, delayed, or incorrect.',
      'AI outputs should not be treated as guaranteed predictions of future market movements.',
      'You are responsible for independently evaluating any information generated by ShTrader before acting upon it.',
      'ShTrader does not guarantee the accuracy, reliability, completeness, or timeliness of AI-generated content.',
    ],
  },
  {
    heading: '6. Risk Management Tools',
    blocks: [
      'ShTrader may provide tools that calculate position size, risk per trade, stop-loss distances, exposure, potential profit and loss, or other risk-management information.',
      'These calculations are estimates based on the information available to the system at the time of calculation.',
      'Actual trading results may differ because of market movements, execution prices, fees, slippage, liquidity, leverage, network conditions, and other factors.',
      'You remain responsible for confirming all transaction parameters before executing a trade.',
    ],
  },
  {
    heading: '7. Blockchain and Smart Contracts',
    blocks: [
      'Certain ShTrader functionality may interact with public blockchain networks and smart contracts.',
      'Blockchain transactions are generally irreversible once confirmed.',
      'You are responsible for:',
      {
        list: [
          'maintaining control of your wallet;',
          'protecting your private keys and recovery phrases;',
          'confirming transaction details before signing;',
          'paying applicable blockchain network fees; and',
          'ensuring that you interact with the correct blockchain network and contract.',
        ],
      },
      'ShTrader will not ask you to provide your private key or wallet recovery phrase.',
      'Loss of access to your wallet, private keys, recovery phrase, or other authentication credentials may result in permanent loss of access to blockchain assets.',
    ],
  },
  {
    heading: '8. Smart Contract Risks',
    blocks: [
      'Blockchain-based functionality may depend on smart contracts, blockchain infrastructure, price oracles, RPC providers, and other third-party infrastructure.',
      'Smart contracts and blockchain infrastructure may contain vulnerabilities, bugs, configuration errors, interruptions, exploits, or other technical risks.',
      'ShTrader does not guarantee that smart contracts or blockchain infrastructure will operate without interruption or error.',
      'By using blockchain functionality, you acknowledge and accept these risks.',
    ],
  },
  {
    heading: '9. Transactions and Fees',
    blocks: [
      'Transactions performed through ShTrader may involve network fees, trading fees, execution fees, or other applicable charges.',
      'Blockchain network fees are determined by the relevant blockchain network and are not controlled by ShTrader.',
      'Before confirming a transaction, you are responsible for reviewing the transaction details and any applicable fees.',
    ],
  },
  {
    heading: '10. Market Data',
    blocks: [
      'ShTrader may obtain market prices, exchange rates, charts, and other financial information from third-party data providers, blockchain oracles, exchanges, and other sources.',
      'Market data may be delayed, unavailable, inaccurate, or different from prices displayed by other providers.',
      'ShTrader does not guarantee that market data is complete, accurate, or available at all times.',
    ],
  },
  {
    heading: '11. TikTok Integration',
    blocks: [
      "ShTrader may allow users to connect their TikTok account and upload content created through ShTrader using TikTok's developer services.",
      'When you connect TikTok:',
      {
        list: [
          'you must authorize the requested permissions;',
          'you remain responsible for the content you upload;',
          "ShTrader does not control TikTok's platform, policies, availability, or moderation decisions; and",
          "your use of TikTok remains subject to TikTok's applicable terms and policies.",
        ],
      },
      'ShTrader is an independent service and is not operated by or affiliated with TikTok.',
      "You may revoke ShTrader's access to your TikTok account through the applicable TikTok account controls.",
    ],
  },
  {
    heading: '12. User Content',
    blocks: [
      'You may create, upload, submit, or otherwise provide content through ShTrader ("User Content").',
      'You retain ownership of your User Content, subject to the rights necessary for ShTrader to operate the Service.',
      'By submitting User Content, you grant ShTrader a limited, non-exclusive license to host, process, transmit, display, and otherwise use the content as reasonably necessary to provide and improve the Service.',
      'You represent that you have the necessary rights to any content you submit.',
      'You must not use ShTrader to upload or distribute content that:',
      {
        list: [
          "infringes another person's intellectual-property rights;",
          'violates applicable law;',
          'contains malicious software;',
          'impersonates another person or organization;',
          'contains fraudulent or deceptive information; or',
          'violates applicable third-party platform policies.',
        ],
      },
    ],
  },
  {
    heading: '13. Prohibited Activities',
    blocks: [
      'You agree not to:',
      {
        list: [
          'use ShTrader for unlawful activities;',
          'attempt to gain unauthorized access to the Service;',
          'interfere with the security or operation of the Service;',
          'exploit vulnerabilities without authorization;',
          'manipulate or abuse trading systems;',
          'use automated systems to attack or overload the Service;',
          'submit malicious code;',
          'impersonate another person;',
          'use ShTrader to facilitate fraud; or',
          'circumvent technical or security restrictions.',
        ],
      },
      'ShTrader may suspend or terminate access where it reasonably believes these Terms have been violated.',
    ],
  },
  {
    heading: '14. Third-Party Services',
    blocks: [
      'ShTrader may rely on third-party services, including blockchain networks, infrastructure providers, market-data providers, cloud providers, analytics services, authentication providers, and social-media platforms.',
      "Third-party services are outside ShTrader's direct control.",
      'ShTrader is not responsible for interruptions, errors, policy changes, security incidents, or other failures originating from third-party services.',
    ],
  },
  {
    heading: '15. Availability',
    blocks: [
      'We aim to keep ShTrader available and reliable, but we do not guarantee uninterrupted access.',
      'The Service may become unavailable because of:',
      {
        list: [
          'maintenance;',
          'software updates;',
          'blockchain network conditions;',
          'infrastructure failures;',
          'third-party service outages;',
          'security incidents;',
          'market-data failures;',
          'network problems; or',
          'circumstances beyond our reasonable control.',
        ],
      },
    ],
  },
  {
    heading: '16. Intellectual Property',
    blocks: [
      'The ShTrader name, branding, software, website design, original content, interfaces, graphics, and other proprietary materials are owned by or licensed to ShTrader unless otherwise stated.',
      "You may not copy, modify, distribute, sell, reverse engineer, or commercially exploit ShTrader's proprietary materials except as permitted by applicable law or with our written permission.",
    ],
  },
  {
    heading: '17. Disclaimers',
    blocks: [
      'To the maximum extent permitted by applicable law, the Service is provided on an "as is" and "as available" basis.',
      'ShTrader makes no warranty that:',
      {
        list: [
          'the Service will always be available;',
          'information will always be accurate;',
          'AI outputs will always be correct;',
          'market data will always be current;',
          'transactions will always execute successfully;',
          'smart contracts will be free from vulnerabilities; or',
          "the Service will meet every user's particular requirements.",
        ],
      },
    ],
  },
  {
    heading: '18. Limitation of Liability',
    blocks: [
      'To the maximum extent permitted by applicable law, ShTrader shall not be liable for indirect, incidental, consequential, special, or punitive losses arising from or relating to your use of the Service.',
      'This includes losses resulting from trading decisions, market movements, blockchain transactions, wallet loss, smart-contract failures, network failures, third-party services, inaccurate market information, or AI-generated information.',
      'Nothing in these Terms excludes liability that cannot legally be excluded under applicable law.',
    ],
  },
  {
    heading: '19. Indemnification',
    blocks: [
      'To the extent permitted by applicable law, you agree to indemnify and hold harmless ShTrader and its contributors, developers, and service providers from claims, losses, liabilities, damages, and expenses arising from:',
      {
        list: [
          'your violation of these Terms;',
          'your unlawful use of the Service;',
          'your User Content; or',
          "your violation of another person's rights.",
        ],
      },
    ],
  },
  {
    heading: '20. Suspension and Termination',
    blocks: [
      'We may suspend or terminate your access to ShTrader if:',
      {
        list: [
          'you violate these Terms;',
          'your activity creates security or legal risks;',
          'required by law or a competent authority; or',
          'we discontinue or materially change the Service.',
        ],
      },
      'You may stop using ShTrader at any time.',
      'Provisions that by their nature should survive termination will continue to apply.',
    ],
  },
  {
    heading: '21. Changes to These Terms',
    blocks: [
      'We may update these Terms from time to time.',
      'When material changes are made, we may update the "Last Updated" date and provide additional notice where appropriate.',
      'Your continued use of ShTrader after changes become effective constitutes acceptance of the updated Terms.',
    ],
  },
  {
    heading: '22. Governing Law',
    blocks: [
      'These Terms shall be interpreted in accordance with applicable laws.',
      'Where legally applicable, disputes shall be subject to the jurisdiction of the competent courts of Nigeria.',
      'Nothing in this section prevents you from exercising mandatory consumer or statutory rights that cannot legally be waived.',
    ],
  },
  {
    heading: '23. Contact',
    blocks: [
      'If you have questions about these Terms, contact:',
      'Email: support@shtrader.app',
      'Website: https://shtrader.app',
    ],
  },
]

const Terms = () => (
  <LegalDocument
    title="Terms of Service"
    lastUpdated="September 19, 2026"
    metaDescription="ShTrader Terms of Service: eligibility, trading and market risk, AI features, blockchain and smart-contract risks, fees, and user responsibilities."
    intro={[
      'Welcome to ShTrader.',
      'These Terms of Service ("Terms") govern your access to and use of the ShTrader website, applications, trading tools, educational resources, artificial-intelligence features, blockchain functionality, and related services (collectively, the "Service").',
      'By accessing or using ShTrader, you agree to these Terms. If you do not agree with these Terms, please do not use the Service.',
    ]}
    sections={sections}
    otherDocument={{ label: 'Read our Privacy Policy', to: '/privacy' }}
  />
)

export default Terms
