/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PriceOracle } from "./PriceOracle";
export type { TokenizedCurrency } from "./TokenizedCurrency";
export type { TradingContract } from "./TradingContract";
export type { TradingPlatform } from "./TradingPlatform";
