/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PriceOracle {
  export type PriceDataStruct = {
    price: BigNumberish;
    timestamp: BigNumberish;
    roundId: BigNumberish;
    isValid: boolean;
  };

  export type PriceDataStructOutput = [
    price: bigint,
    timestamp: bigint,
    roundId: bigint,
    isValid: boolean
  ] & { price: bigint; timestamp: bigint; roundId: bigint; isValid: boolean };
}

export interface PriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDecimals"
      | "getExchangeRate"
      | "getLatestPrice"
      | "getLatestValidPrice"
      | "hasPriceFeed"
      | "maxStaleness"
      | "minConfidence"
      | "owner"
      | "priceFeeds"
      | "renounceOwnership"
      | "setMaxStaleness"
      | "setPriceFeed"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaxStalenessUpdated"
      | "OwnershipTransferred"
      | "PriceFeedUpdated"
      | "PriceRequested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getDecimals", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getExchangeRate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestValidPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPriceFeed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "maxStaleness",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minConfidence",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "priceFeeds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxStaleness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceFeed",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestValidPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxStaleness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minConfidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxStaleness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MaxStalenessUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceFeedUpdatedEvent {
  export type InputTuple = [pair: string, feedAddress: AddressLike];
  export type OutputTuple = [pair: string, feedAddress: string];
  export interface OutputObject {
    pair: string;
    feedAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceRequestedEvent {
  export type InputTuple = [
    pair: string,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [pair: string, price: bigint, timestamp: bigint];
  export interface OutputObject {
    pair: string;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PriceOracle;
  waitForDeployment(): Promise<this>;

  interface: PriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDecimals: TypedContractMethod<[pair: string], [bigint], "view">;

  getExchangeRate: TypedContractMethod<
    [baseCurrency: string, quoteCurrency: string],
    [bigint],
    "view"
  >;

  getLatestPrice: TypedContractMethod<
    [pair: string],
    [PriceOracle.PriceDataStructOutput],
    "view"
  >;

  getLatestValidPrice: TypedContractMethod<[pair: string], [bigint], "view">;

  hasPriceFeed: TypedContractMethod<[pair: string], [boolean], "view">;

  maxStaleness: TypedContractMethod<[], [bigint], "view">;

  minConfidence: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  priceFeeds: TypedContractMethod<[arg0: string], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMaxStaleness: TypedContractMethod<
    [newMaxStaleness: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPriceFeed: TypedContractMethod<
    [pair: string, feedAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDecimals"
  ): TypedContractMethod<[pair: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExchangeRate"
  ): TypedContractMethod<
    [baseCurrency: string, quoteCurrency: string],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestPrice"
  ): TypedContractMethod<
    [pair: string],
    [PriceOracle.PriceDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestValidPrice"
  ): TypedContractMethod<[pair: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasPriceFeed"
  ): TypedContractMethod<[pair: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxStaleness"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minConfidence"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceFeeds"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxStaleness"
  ): TypedContractMethod<[newMaxStaleness: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceFeed"
  ): TypedContractMethod<
    [pair: string, feedAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MaxStalenessUpdated"
  ): TypedContractEvent<
    MaxStalenessUpdatedEvent.InputTuple,
    MaxStalenessUpdatedEvent.OutputTuple,
    MaxStalenessUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceFeedUpdated"
  ): TypedContractEvent<
    PriceFeedUpdatedEvent.InputTuple,
    PriceFeedUpdatedEvent.OutputTuple,
    PriceFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PriceRequested"
  ): TypedContractEvent<
    PriceRequestedEvent.InputTuple,
    PriceRequestedEvent.OutputTuple,
    PriceRequestedEvent.OutputObject
  >;

  filters: {
    "MaxStalenessUpdated(uint256,uint256)": TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;
    MaxStalenessUpdated: TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceFeedUpdated(string,address)": TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;
    PriceFeedUpdated: TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;

    "PriceRequested(string,int256,uint256)": TypedContractEvent<
      PriceRequestedEvent.InputTuple,
      PriceRequestedEvent.OutputTuple,
      PriceRequestedEvent.OutputObject
    >;
    PriceRequested: TypedContractEvent<
      PriceRequestedEvent.InputTuple,
      PriceRequestedEvent.OutputTuple,
      PriceRequestedEvent.OutputObject
    >;
  };
}
