/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TradingContractInterface extends Interface {
  getFunction(
    nameOrSignature: "closePosition" | "openPosition" | "userPositions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PositionClosed" | "PositionOpened"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closePosition",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "openPosition",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPositions",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPositions",
    data: BytesLike
  ): Result;
}

export namespace PositionClosedEvent {
  export type InputTuple = [
    user: AddressLike,
    pair: string,
    amount: BigNumberish,
    exitPrice: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    pair: string,
    amount: bigint,
    exitPrice: bigint
  ];
  export interface OutputObject {
    user: string;
    pair: string;
    amount: bigint;
    exitPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenedEvent {
  export type InputTuple = [
    user: AddressLike,
    pair: string,
    amount: BigNumberish,
    entryPrice: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    pair: string,
    amount: bigint,
    entryPrice: bigint
  ];
  export interface OutputObject {
    user: string;
    pair: string;
    amount: bigint;
    entryPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TradingContract extends BaseContract {
  connect(runner?: ContractRunner | null): TradingContract;
  waitForDeployment(): Promise<this>;

  interface: TradingContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closePosition: TypedContractMethod<[_pair: string], [void], "nonpayable">;

  openPosition: TypedContractMethod<
    [
      _pair: string,
      _amount: BigNumberish,
      _entryPrice: BigNumberish,
      _stopLoss: BigNumberish,
      _takeProfit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        pair: string;
        amount: bigint;
        entryPrice: bigint;
        stopLoss: bigint;
        takeProfit: bigint;
        isOpen: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closePosition"
  ): TypedContractMethod<[_pair: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "openPosition"
  ): TypedContractMethod<
    [
      _pair: string,
      _amount: BigNumberish,
      _entryPrice: BigNumberish,
      _stopLoss: BigNumberish,
      _takeProfit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        pair: string;
        amount: bigint;
        entryPrice: bigint;
        stopLoss: bigint;
        takeProfit: bigint;
        isOpen: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PositionClosed"
  ): TypedContractEvent<
    PositionClosedEvent.InputTuple,
    PositionClosedEvent.OutputTuple,
    PositionClosedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpened"
  ): TypedContractEvent<
    PositionOpenedEvent.InputTuple,
    PositionOpenedEvent.OutputTuple,
    PositionOpenedEvent.OutputObject
  >;

  filters: {
    "PositionClosed(address,string,uint256,uint256)": TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;
    PositionClosed: TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;

    "PositionOpened(address,string,uint256,uint256)": TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
    PositionOpened: TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
  };
}
